image: node:latest

stages:
  - testing

E2E-Testing:
  stage: testing
  script:
    - chmod +x pipeline-assets/scripts/*
    - pipeline-assets/scripts/install-basic-libraries.sh
    - pipeline-assets/scripts/install-java-maven.sh
    - pipeline-assets/scripts/install-chrome-browser.sh
    - pipeline-assets/scripts/install-chrome-driver.sh

    - mvn test

  artifacts:
    when: always
    expire_in: 4 days
    paths:
      - test-output